Initial SBOM support
DataDog/datadog-ci pull request #1036
Opened 2023-08-15 19:25 UTC by juli1

### What and why?

 - **What**: we want to add support to upload SBOM payload to Datadog endpoint.
 - **Why**: we want to offer a new feature to review SBOM

### How?

This PR is the first PR to introduce support for SBOM file upload. It works as follow

1. Check the file is valid
2. Generate the protobuf representation of the data
3. Upload the data to the intake endpoint.

**Important notes**
 - Opposite to existing features, we do not make use of the concurrency as we need to only upload one or two files.
 - We do not use any renderer (at least for now) and tried to keep the code very minimal
 - When running `yarn install`, some dependencies were updated and broke the existing code. We had to add new `resolutions` to `package.json`

### Review checklist

- [ ] Add unit test

2023-08-15 20:26 UTC, dastrong requested changes

2023-08-15 20:26 UTC, dastrong commented on src/helpers/tags.ts
> + * Get SPAN tags get the tags to upload results in CI for the following commands: sarif and sbom.
```suggestion
 * Get the tags to upload results in CI for the following commands: sarif and sbom.
```

2023-08-15 20:26 UTC, dastrong commented on src/helpers/config.ts
> +  envVarTags: string | undefined
```suggestion
  apiKey?: string
  env?: string
  envVarTags?: string
```

2023-08-15 20:26 UTC, dastrong commented on src/helpers/api.ts
> +import {apiConstructor} from '../commands/sarif/api'
```suggestion
import chalk from 'chalk'
import {APIHelper} from '../commands/sarif/interfaces'
import {apiConstructor} from '../commands/sarif/api'
import {DATADOG_SITE_US1} from '../constants'
```

2023-08-15 20:26 UTC, dastrong commented on src/commands/sbom/README.md
> + - `DD_SERVICE`: the Datadog service you use
This doesn't need to be defined since you can pass in `--service some-service` though?

2023-08-16 00:37 UTC, juli1 commented
rebase not clean, opened a clean pull request here https://github.com/DataDog/datadog-ci/pull/1038

2023-08-16 00:37 UTC, closed without merging