Add SBOM checker in staging
DataDog/datadog-ci pull request #1109
Opened 2023-11-09 22:23 UTC by juli1

### What and why?

Re-enabled SBOM e2e test with staging.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)

2023-11-09 22:32 UTC, dastrong approved these changes

2023-11-10 09:33 UTC, Drarig29 approved these changes

2023-11-10 10:10 UTC, Drarig29 requested changes
Actually, I'll dismiss my approval since I think something is not working ([see CI](https://github.com/DataDog/datadog-ci/actions/runs/6818134117/job/18543188642?pr=1109#step:11:8)):

![image](https://github.com/DataDog/datadog-ci/assets/9317502/fe6b7fa0-eeb1-4513-8fce-2710bfadff49)

You are having a 404 error, but the CI succeeds 😁

2023-12-06 09:26 UTC, Drarig29 approved these changes
LGTM

2023-12-06 11:32 UTC, merged