[SYNTH-12971] Make executeTests backwards compatible
DataDog/datadog-ci pull request #1293
Opened 2024-04-25 13:05 UTC by teodor2312

### What and why?

A short description of what changes this PR introduces and why.

### How?

A brief description of implementation details of this PR.

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)

2024-04-26 14:56 UTC, Drarig29 commented on src/commands/synthetics/interfaces.ts
> +}
Can you change `LegacyRunTestsCommandConfig` to `extends Omit<>` from the other interface?

2024-04-29 09:05 UTC, Drarig29 commented on src/commands/synthetics/__tests__/run-tests-lib.test.ts
> +    })
missing new line
```suggestion
    })

```

2024-04-29 09:41 UTC, Drarig29 approved these changes
~~LGTM~~ **Edit**: see comment below

2024-05-02 10:39 UTC, Drarig29 requested changes
People still using code like `const config: synthetics.RunTestsCommandConfig = ...` will have TS complain with:

```ts
error TS2322: Type '{ apiKey: string; appKey: string; configPath: string; datadogSite: string; failOnCriticalErrors: false; failOnMissingTests: false; failOnTimeout: true; files: string[]; global: {}; locations: never[]; ... 6 more ...; variableStrings: never[]; }' is not assignable to type 'RunTestsCommandConfig'.
  Object literal may only specify known properties, and 'global' does not exist in type 'RunTestsCommandConfig'.

12   global: {},
     ~~~~~~~~~~
```

2024-05-02 15:21 UTC, teodor2312 commented on src/commands/synthetics/run-tests-command.ts
> +    if (isUsingGlobal(this.config, this.reporter)) {
It is yes :D i messaged you that in slack :D i'm considering if i shouldn't just remove the `isUsingGlobal` function completely and going back to the if statements i already had before 🤔

2024-05-02 15:22 UTC, teodor2312 commented on src/commands/synthetics/run-tests-command.ts
> +    if (isUsingGlobal(this.config, this.reporter)) {
yeah i think i'll do that 🤔

2024-05-16 08:29 UTC, Drarig29 commented on src/commands/synthetics/run-tests-lib.ts
> +import {replaceGlobalWithDefaultTestOverrides} from './compatability'
```suggestion
import {replaceGlobalWithDefaultTestOverrides} from './compatibility'
```

2024-05-16 09:34 UTC, teodor2312 commented on src/commands/synthetics/run-tests-lib.ts
> +import {replaceGlobalWithDefaultTestOverrides} from './compatability'
🤦 oops will change it :D

2024-05-16 10:00 UTC, Drarig29 approved these changes
LGTM

2024-05-16 10:07 UTC, merged