[SYNTH-14344] Do not require etag from app part upload
DataDog/datadog-ci pull request #1301
Opened 2024-05-09 21:06 UTC by kevin-pietsch

### What and why?

Do not require the etag header be returned when uploading mobile application parts. Azure strictly does not return the etag header.

### How?

Just default to empty string for etag field when completing upload. The backend for azure expects this behavior

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)

2024-05-10 11:29 UTC, teodor2312 approved these changes
LGTM

2024-05-10 11:33 UTC, teodor2312 commented
Hey i noticed that there are tests for this tag is it possible to add a test case for empty string?

https://github.com/DataDog/datadog-ci/blob/a4041c4fca346122fa54dd67dad3d93d4f1731b9/src/commands/synthetics/__tests__/api.test.ts#L261-L290

2024-05-10 11:51 UTC, Drarig29 requested changes
The `ETag` should uniquely represent the request resource for caching (see [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)). Defaulting it to an empty string means that all resources will be seen as the same, which could cause caching issues.

It would be better to not return an `ETag` property at all if it's falsy (empty string included).

2024-05-17 15:35 UTC, kevin-pietsch commented
> The `ETag` should uniquely represent the request resource for caching (see [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)). Defaulting it to an empty string means that all resources will be seen as the same, which could cause caching issues.
> 
> It would be better to not return an `ETag` property at all if it's falsy (empty string included).

@Drarig29 This is not setting any `ETag` headers to empty string -- we don't actually return any ETags, this is related to the behavior of the different cloud providers. We pass the ETag value from provider up to dogweb backend. In particular we return it because AWS S3 uses it as part of their object integrity check: https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html

So right now this isn't used for caching in any meaningful way and we are not setting any ETag headers with it, so I don't think any concerns there.

I do agree that it would be better to have it explicitly optional in this code it was just significantly more painful as we need to change the API schema to allow that in dogweb, and I'd argue the value is fairly limited. 

But I can make the change -- I'll update here after modifying dogweb.

2024-05-17 15:38 UTC, kevin-pietsch commented
> Hey i noticed that there are tests for this tag is it possible to add a test case for empty string?
> 
> https://github.com/DataDog/datadog-ci/blob/a4041c4fca346122fa54dd67dad3d93d4f1731b9/src/commands/synthetics/__tests__/api.test.ts#L261-L290

I think this will be impacted by making it explicitly optional (discussed [https://github.com/DataDog/datadog-ci/pull/1301#issuecomment-2117863639](here)) -- but will add an explicit test with the update for present vs. non-present ETag field

2024-05-17 16:02 UTC, Drarig29 commented
Discussed it offline, and we agreed it was OK to keep the empty string, and just add a unit test about it.

2024-05-21 15:34 UTC, Drarig29 commented on src/commands/synthetics/api.ts
> +    // Azure part-upload does not return ETag -- set to empty string
I still think it's useful to say _why_ is an empty string OK in our very specific case
```suggestion
    // Azure part-upload does not return ETag headers, and our backend ignores it for Azure
```

2024-05-21 15:45 UTC, Drarig29 approved these changes
LGTM

2024-05-21 16:21 UTC, merged