[PROF-4993] Remove dependencies command
DataDog/datadog-ci pull request #482
Opened 2022-02-21 09:58 UTC by PyvesB

### What and why?

Our Snyk integration has been sunset, the dependencies command is consequently no longer needed.

### How?

Removes the `dependencies` folder and mentions in the Readme.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)

2022-02-21 12:56 UTC, flodav approved these changes

2022-02-28 10:14 UTC, juan-fernandez approved these changes

2022-02-28 10:20 UTC, sdeprez approved these changes

2022-02-28 10:21 UTC, juan-fernandez requested changes
I just noticed that standalone binary tests should be failing because of this. Is the branch up to date with `master`?

2022-02-28 10:26 UTC, juan-fernandez commented
it should be as simple as removing this test: https://github.com/DataDog/datadog-ci/blob/master/standalone-e2e/standalone-binary.test.ts#L21-L27

2022-02-28 10:30 UTC, juan-fernandez approved these changes
thanks!

2022-02-28 11:37 UTC, m-rousse approved these changes

2022-02-28 11:52 UTC, merged