[SYNTH-3284] Update `startUrlSubstitutionRegex` to support pipe syntax
DataDog/datadog-ci pull request #755
Opened 2023-01-23 17:14 UTC by jakepruitt

### What and why?

In order to manage the `startUrlSubstitutionRegex` difficulties with supporting `/` characters in the regular expression, this PR adds support for a pipe-based (`|`) syntax of `your_regex|your_substitution`.

### How?

An update to the documentation

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)

2023-01-23 18:53 UTC, buraizu requested changes
Thanks for the PR, just requested a minor update to the copy.

2023-01-23 18:53 UTC, buraizu commented on src/commands/synthetics/README.md
> +| `startUrlSubstitutionRegex` | String           | The regex to modify the starting URL of the test (for browser and HTTP tests only), whether it was given by the original test or the configuration o
```suggestion
| `startUrlSubstitutionRegex` | String           | The regex to modify the starting URL of the test (for browser and HTTP tests only), whether it was given by the original test or the configuration override `startUrl`. <br><br>If the URL contains variables, this regex applies after the interpolation of the variables. There are two possible formats: <br>- `your_regex\|your_substitution`: A pipe-based regular expression. For example, `https://example.com(.*)\|http://subdomain.example.com$1` to transform `https://example.com/test` to `http://subdomain.example.com/test`. <br>- `s/your_regex/your_substitution/modifiers`: The JavaScript regex syntax for more complex transformations. For example, `s/(https://www.)(.*)/$1extra-$2/` to transform `https://www.example.com` into `https://www.extra-example.com`. |
```

2023-01-24 12:03 UTC, lefebvree approved these changes

2023-01-24 17:31 UTC, buraizu approved these changes

2023-01-25 08:55 UTC, merged